baseURL: https://michaelsrecipes.page/
languageCode: en-us
title: "Michael's Recipe Collection"
defaultContentLanguage: en
paginate: 20
menu:
  main:
    - name: Home
      weight: 1
      url: /
    - name: Categories
      weight: 2
      url: /categories/
    - name: Cuisines
      weight: 3
      url: /cuisines/
    - name: Tags
      weight: 4
      url: /tags/
    - name: Ingredients
      weight: 5
      url: /ingredients/
taxonomies:
  category: categories
  cuisine: cuisines
  tag: tags
  ingredient: ingredients
