baseURL: https://michaelsrecipes.page/
languageCode: en-us
title: "Michael's Recipe Collection"
defaultContentLanguage: en
paginate: 20
menu:
  main:
    - name: Home
      weight: 1
      url: /
    - name: Categories
      weight: 2
      url: /categories/
    - name: Cuisines
      weight: 3
      url: /cuisines/
    - name: Tags
      weight: 4
      url: /tags/
    - name: Ingredients
      weight: 5
      url: /ingredients/
    - name: Equipment
      weight: 6
      url: /equipment/
taxonomies:
  category: categories
  cuisine: cuisines
  tag: tags
  ingredient: ingredients
  equipment: equipment
outputFormats:
  cooking:
    name: cooking
    path: cooking
    isHTML: true
    isPlainText: false
    mediaType: text/html
params:
  ingredient_categories:
    - meat_ingredients: Meat
    - produce_ingredients: Produce
    - egg_and_dairy_ingredients: Eggs & Dairy
    - pantry_ingredients: Pantry
    - freezer_ingredients: Freezer
    - alcohol_ingredients: Alcohol
    - spice_and_seasoning_ingredients: Spices & Seasonings
    - staple_ingredients: Staples
  auto_categorized_ingredients:
    meat_ingredients:
      - beef
      - chicken
      - pork
    produce_ingredients:
      - garlic
      - onion
      - green_onion
      - green_pepper
      - celery
      - carrot
      - potato
      - banana
      - apple
      - raspberry
      - blackberry
      - blueberry
      - strawberry
    egg_and_dairy_ingredients:
      - egg
      - butter
      - milk
      - buttermilk
      - almond_milk
      - sour_cream
      - cheese
      - parmesan
      - mozzarella
      - cheddar
    pantry_ingredients:
      - rice
      - beef_broth
      - tomato_paste
      - pumpkin
      - oat
      - syrup
      - coconut_flake
      - chia_seed
      - chocolate_chip
      - pecan
    alcohol_ingredients:
      - wine
      - beer
      - rum
      - whiskey
      - vodka
    spice_and_seasoning_ingredients:
      - sesame_seeds
      - vanilla
      - cinnamon
      - pumpkin_pie_spice
      - thyme
      - rosemary
      - garlic_powder
      - onion_powder
      - chili_powder
      - paprika
    staple_ingredients:
      - cornstarch
      - vegetable_oil
      - olive_oil
      - oil_spray
      - salt
      - pepper
      - bread_flour
      - ap_flour
      - baking_powder
      - baking_soda
      - sugar
      - powdered_sugar
      - light_brown_sugar
      - dark_brown_sugar
      - yeast
