baseURL: https://michaelsrecipes.page/
languageCode: en-us
title: "Michael's Cookbook"
defaultContentLanguage: en
theme:
  - Cookbook
  - CookbookIconsAndContent
paginate: 12
taxonomies:
  category: categories
  cuisine: cuisines
  tag: tags
  ingredient: ingredients
  equipment: equipment
outputFormats:
  cooking:
    name: cooking
    path: cooking
    isHTML: true
    isPlainText: false
    mediaType: text/html
params:
  logo: "images/noun-chef-5295726.png"
  add_google_data: true
  ingredient_categories:
    - meat_ingredients: Meat
    - produce_ingredients: Produce
    - egg_and_dairy_ingredients: Eggs & Dairy
    - bakery_ingredients: Bakery
    - pantry_ingredients: Pantry
    - freezer_ingredients: Freezer
    - alcohol_ingredients: Alcohol
    - spice_and_seasoning_ingredients: Spices & Seasonings
    - staple_ingredients: Staples
  auto_categorized_ingredients:
    meat_ingredients:
      - beef
      - chicken
      - pork
      - pancetta
      - bacon
      - sausage
    produce_ingredients:
      - garlic
      - onion
      - red_onion
      - green_onion
      - green_pepper
      - bell_pepper
      - zucchini
      - parsley
      - cilantro
      - fresh_oregano
      - fresh_thyme
      - fresh_rosemary
      - fresh_basil
      - romaine
      - celery
      - carrot
      - potato
      - tomato
      - tomatillo
      - banana
      - apple
      - raspberry
      - blackberry
      - blueberry
      - strawberry
      - cherry
      - lemon
    egg_and_dairy_ingredients:
      - egg
      - butter
      - unsalted_butter
      - milk
      - half_and_half
      - buttermilk
      - almond_milk
      - sour_cream
      - cheese
      - parmesan
      - fresh_mozzarella
      - mozzarella
      - cheddar
      - provolone
      - jack_cheese
      - mayonnaise
    bakery_ingredients:
      - bread
    pantry_ingredients:
      - rice
      - pasta
      - corn_tortilla
      - flour_tortilla
      - spaghetti
      - chicken_broth
      - chicken_bouillon
      - beef_broth
      - beef_bouillon
      - bachan
      - worcestershire
      - gochujang
      - achiote
      - tomato_paste
      - sundried_tomato
      - canned_whole_tomato
      - canned_crushed_tomato
      - guajillo_chili
      - california_chili
      - arbol_chili
      - balsamic_vinegar
      - red_wine_vinegar
      - artichoke_hearts
      - banana_peppers
      - beans
      - pumpkin
      - oat
      - syrup
      - coconut_flake
      - chia_seed
      - chocolate_chip
      - pecan
      - pistachio
      - jelly
    alcohol_ingredients:
      - wine
      - beer
      - guinness
      - rum
      - whiskey
      - vodka
    spice_and_seasoning_ingredients:
      - sesame_seeds
      - vanilla
      - cinnamon
      - pumpkin_pie_spice
      - cardamom
      - allspice
      - ground_clove
      - clove
      - ground_ginger
      - dried_thyme
      - dried_rosemary
      - dried_basil
      - dried_oregano
      - italian_seasoning
      - bay_leaf
      - garlic_powder
      - onion_powder
      - chili_powder
      - paprika
      - cumin
      - cumin_seed
      - cayenne
      - red_pepper_flakes
    staple_ingredients:
      - cornstarch
      - vegetable_oil
      - olive_oil
      - oil_spray
      - salt
      - black_pepper
      - bread_flour
      - ap_flour
      - baking_powder
      - baking_soda
      - sugar
      - powdered_sugar
      - light_brown_sugar
      - dark_brown_sugar
      - yeast
      - water
  credits: "
    [Menu](https://thenounproject.com/browse/icons/term/menu/) and
    [Book](https://thenounproject.com/browse/icons/term/book/)
    icons by ABDUL LATIF from Noun Project.
    
    
    Sous Vide by Walker B Milhoan from [Noun Project](https://thenounproject.com/browse/icons/term/sous-vide/)
    
    
    Pressure Cooker by Mitchell Fong from [Noun Project](https://thenounproject.com/browse/icons/term/pressure-cooker/)
    
    
    [Stand Mixer](https://thenounproject.com/browse/icons/term/stand-mixer/),
    [Oven](https://thenounproject.com/browse/icons/term/oven/), and
    [Appliance](https://thenounproject.com/browse/icons/term/appliance/)
    icons by Made from Noun Project
    
    
    Rice Cooker by Samsul Rizal from [Noun Project](https://thenounproject.com/browse/icons/term/rice-cooker/)
    
    
    [Blender](https://thenounproject.com/browse/icons/term/blender/),
    [Juicer](https://thenounproject.com/browse/icons/term/juicer/), and
    [immersion blender](https://thenounproject.com/browse/icons/term/immersion-blender/)
    icons by Yazmin Alanis from Noun Project
    
    
    Cast iron skillet by W Fully from [Noun Project](https://thenounproject.com/browse/icons/term/cast-iron-skillet/)
    
    
    Dutch Oven by Lars Meiertoberens from [Noun Project](https://thenounproject.com/browse/icons/term/dutch-oven/)
    
    
    chef by Amethyst Studio from [Noun Project](https://thenounproject.com/browse/icons/term/chef/)</a>
    "
  social_accounts:
    mastodon:
      server: mwtaylor.social
      username: Michael
    github:
      username: mwtaylor
      repository: recipes
